swimmer_table = [
        [''], # Name, age, DOB, empty cell
        [''], # Actuals, empty cell, empty cell, empty cell
        [''], # Time, Date, Standard, empty cell
        ['25 Y Free'],
        ['50 Y Free'],
        ['100 Y Free'],
        ['200 Y Free'],
        ['500 Y Free'],
        ['1000 Y Free'],
        ['25 Y Back'],
        ['50 Y Back'],
        ['100 Y Back'],
        ['200 Y Back'],
        ['25 Y Fly'],
        ['50 Y Fly'],
        ['100 Y Fly'],
        ['200 Y Fly'],
        ['25 Y Breast'],
        ['50 Y Breast'],
        ['100 Y Breast'],
        ['200 Y Breast'],
        ['100 Y IM'],
        ['200 Y IM'],
        ['400 Y IM'],
        [''],
        ['50 M Free'],
        ['100 M Free'],
        ['200 M Free'],
        ['400 M Free'],
        ['800 M Free'],
        ['50 M Back'],
        ['100 M Back'],
        ['200 M Back'],
        ['50 M Fly'],
        ['100 M Fly'],
        ['50 M Breast'],
        ['100 M Breast'],
        ['200 M Breast'],
        ['200 M IM'],
        ['400 M IM']
    ]